USE MealMasterDb;

CREATE TABLE IF NOT EXISTS MessureType(
	Id VARCHAR(36) PRIMARY KEY,
    Type VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS Messure(
	Id VARCHAR(36) PRIMARY KEY,
	ShortName VARCHAR(5) UNIQUE NOT NULL,
    FullName VARCHAR(50) UNIQUE NOT NULL,
    RelativeSize FLOAT NOT NULL,
	MessureTypeId VARCHAR(36) NOT NULL,
    
    FOREIGN KEY (MessureTypeId) REFERENCES MessureType(Id) 
		ON UPDATE RESTRICT 
        ON DELETE RESTRICT 
);

CREATE TABLE IF NOT EXISTS SourceType (
	Id VARCHAR(36) PRIMARY KEY,
    Type VARCHAR(36) UNIQUE NOT NULL 
);

CREATE TABLE IF NOT EXISTS Source (
	Id VARCHAR(36) PRIMARY KEY ,
    TypeId VARCHAR(36)  NOT NULL,
    Text VARCHAR(200) NOT NULL,
    
    FOREIGN KEY (TypeId) REFERENCES SourceType(Id)
		ON UPDATE RESTRICT
        ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS Ingredient(
	Id VARCHAR(36) PRIMARY KEY,
    Name VARCHAR(200) NOT NULL,
    MessureTypeId VARCHAR(36) NOT NULL,
    WeightVolumeRatio FLOAT NOT NULL DEFAULT 1,
    NutrientSourceId VARCHAR(36) NOT NULL,
	
    FOREIGN KEY (MessureTypeId) REFERENCES MessureType(Id)
		ON UPDATE RESTRICT 
        ON DELETE RESTRICT,
	FOREIGN KEY (NutrientSourceId) REFERENCES Source(Id)
		ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS IngredientCategory(
	Id VARCHAR(36) PRIMARY KEY,
    Name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS Ingredient_IngredientCategory(
	Id VARCHAR(36) PRIMARY KEY,
    IngredientId VARCHAR(36) NOT NULL,
    IngredientCategoryId VARCHAR(36) NOT NULL,
    
    FOREIGN KEY (IngredientId) REFERENCES ingredient(Id)
        ON DELETE CASCADE,
    FOREIGN KEY (IngredientCategoryId) REFERENCES IngredientCategory(Id)
		ON UPDATE RESTRICT
        ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS NutrientType (
	Id VARCHAR(36) PRIMARY KEY,
    Name VARCHAR(200) UNIQUE NOT NULL,
    MessureId VARCHAR(36) NOT NULL,
	DisplayIndex SMALLINT NOT NULL,
    Mandatory BOOL NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS NutrientIngredient (
	Id VARCHAR(36) PRIMARY KEY,
    IngredientId VARCHAR(36) NOT NULL,
    NutrientTypeId VARCHAR(36) NOT NULL,
    Value FLOAT NOT NULL DEFAULT 0,
    
    FOREIGN KEY (IngredientId) REFERENCES Ingredient(Id)
		ON DELETE CASCADE,
	FOREIGN KEY (NutrientTypeId) REFERENCES NutrientType(Id)
		ON UPDATE RESTRICT
        ON DELETE RESTRICT
);

CREATE TABLE RecipeContinentOrgin(
	Id VARCHAR(36) PRIMARY KEY,
    Continent VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE RecipeCountryOrgin(
	Id VARCHAR(36) PRIMARY KEY,
    Country VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS Recipe(
	Id VARCHAR(36) PRIMARY KEY,
    Title VARCHAR(200) NOT NULL,
	Description TEXT NOT NULL,
    Portions SMALLINT NOT NULL,
    RecipeContinentOrginId VARCHAR(36),
    RecipeCountryOrginId VARCHAR(36),
    SourceId VARCHAR(36) NOT NULL,
    
    FOREIGN KEY (RecipeContinentOrginId) REFERENCES RecipeContinentOrgin(Id) 
		ON DELETE RESTRICT,
    FOREIGN KEY (RecipeCountryOrginId) REFERENCES RecipeCountryOrgin(iD)
		ON DELETE RESTRICT,
    FOREIGN KEY (SourceId) REFERENCES Source(Id)
		ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS RecipeCategory(
	Id VARCHAR(36) PRIMARY KEY,
    Name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS RecipeIngredient(
	Id VARCHAR(36) PRIMARY KEY,
    IngredientId VARCHAR(36) NOT NULL,
    MessureId VARCHAR(36) NOT NULL,
    Amount FLOAT NOT NULL,
    
    FOREIGN KEY (IngredientId) REFERENCES Ingredient(Id)
		ON DELETE RESTRICT,
    FOREIGN KEY (MessureId) REFERENCES Messure(Id)
        ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS RecipeStep(
	Id VARCHAR(36) PRIMARY KEY,
    RecipeId VARCHAR(36) NOT NULL,
    StepIndex SMALLINT NOT NULL,
    Text TEXT NOT NULL,
	
    FOREIGN KEY (RecipeId) REFERENCES Recipe(Id) 
		ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Recipe_RecipeCategory(
	Id VARCHAR(36) PRIMARY KEY,
    RecipeId VARCHAR(36) NOT NULL,
	RecipeCategoryId VARCHAR(36) NOT NULL,
    
    FOREIGN KEY (RecipeId) REFERENCES Recipe(Id)
		ON DELETE CASCADE,
    FOREIGN KEY (RecipeCategoryId) REFERENCES RecipeCategory(Id)
		ON DELETE RESTRICT
)
